spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://192.168.188.11:1433;DatabaseName=UFDATA_608_2016
    username: sa
    password: ABC123abc

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.domain
pagehelper:
  helper-dialect: sqlserver
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
  pageSizeZero: true

logging:
  level:
    com.example.demo.mapper: debug