spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cd-cdb-217paoj2.sql.tencentcdb.com:63263/ryncdcxttest?serverTimezone=PRC
    username: root
    password: jc86937378

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.domain
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
  pageSizeZero: true

logging:
  level:
    com.example.demo.mapper: debug